#!/usr/bin/env python3
"""
Vendor Google Fonts locally so the PWA is genuinely offline-capable.

Downloads the latin + latin-ext woff2 subsets for the app's two families and
writes public/fonts/fonts.css with rewritten local URLs.

Run from the repo root:  python3 scripts/vendor-fonts.py
"""
import os
import pathlib
import re
import urllib.request

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Fraunces:opsz,wght@9..144,500;9..144,700;9..144,800"
    "&family=Nunito:wght@400;600;700;800&display=swap"
)
# Modern UA so Google serves woff2 rather than legacy formats.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
KEEP_SUBSETS = {"latin", "latin-ext"}
OUT_DIR = pathlib.Path("public/fonts")


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})
    ).read()


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css = fetch(GOOGLE_CSS).decode("utf-8")

    blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    rules: list[str] = []
    downloaded: dict[str, str] = {}

    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        url_match = re.search(r"url\((https://fonts\.gstatic\.com[^)]+)\)", block)
        family_match = re.search(r"font-family:\s*'([^']+)'", block)
        if not url_match or not family_match:
            continue

        url = url_match.group(1)
        family = family_match.group(1).replace(" ", "")
        weight_match = re.search(r"font-weight:\s*([^;]+);", block)
        weight = weight_match.group(1).strip().replace(" ", "-") if weight_match else "regular"
        filename = f"{family}-{weight}-{subset}.woff2".lower()

        if url not in downloaded:
            data = fetch(url)
            (OUT_DIR / filename).write_bytes(data)
            downloaded[url] = filename
            print(f"  downloaded {filename} ({len(data) // 1024}KB)")

        rules.append(f"/* {subset} */\n{block.replace(url, f'/fonts/{downloaded[url]}')}")

    header = (
        "/* Self-hosted fonts - keeps the PWA genuinely offline-capable.\n"
        " * Generated by scripts/vendor-fonts.py - do not hand-edit.\n"
        " */\n\n"
    )
    (OUT_DIR / "fonts.css").write_text(header + "\n\n".join(rules) + "\n")
    print(f"\nWrote {OUT_DIR / 'fonts.css'} with {len(rules)} @font-face rules")


if __name__ == "__main__":
    main()

